Repository Qiskit/qiskit-addon-sqd, pull requests merged in 2024-09, with the labels that each got.

#5 Documentation adjustments
  README.md
  docs/conf.py
  docs/how_tos/choose_subspace_dimension.ipynb
  docs/how_tos/integrate_dice_solver.ipynb
  docs/index.rst
  docs/release-notes.rst
  docs/tutorials/01_chemistry_hamiltonian.ipynb
  docs/tutorials/02_qubit_hamiltonian.ipynb
  pyproject.toml
  qiskit_addon_sqd/configuration_recovery.py
  qiskit_addon_sqd/qubit.py
  releasenotes/config.yaml
  releasenotes/notes/.gitkeep
  test/README.md
  tox.ini
Labels: stable backport potential

#10 Add qubit functions to the API docs
  qiskit_addon_sqd/qubit.py
Labels: stable backport potential

#14 Set earliest version in reno
  releasenotes/config.yaml
Labels: stable backport potential

#18 Fix release note
  releasenotes/notes/0.5/hamming-kwarg-c73098a4c756453e.yaml
Labels: stable backport potential

#20 Update arg name in release note
  releasenotes/notes/0.5/hamming-kwarg-c73098a4c756453e.yaml
Labels: stable backport potential

#24 Minor tutorial updates
  docs/tutorials/01_chemistry_hamiltonian.ipynb
  docs/tutorials/02_qubit_hamiltonian.ipynb
Labels: documentation, stable backport potential

#28 Link to addons page on landing pages
  README.md
  docs/index.rst
Labels: documentation, stable backport potential

#34 Clean up tutorials
  docs/tutorials/01_chemistry_hamiltonian.ipynb
  docs/tutorials/02_qubit_hamiltonian.ipynb
Labels: documentation, stable backport potential

#36 Update dated license blurbs.
  docs/conf.py
  pyproject.toml
  qiskit_addon_sqd/__init__.py
  qiskit_addon_sqd/configuration_recovery.py
  qiskit_addon_sqd/counts.py
  qiskit_addon_sqd/fermion.py
  qiskit_addon_sqd/qubit.py
  qiskit_addon_sqd/subsampling.py
  test/__init__.py
  test/test_configuration_recovery.py
  test/test_counts.py
  test/test_fermion.py
  test/test_qubit.py
  test/test_subsampling.py
  test/test_workflow.py
Labels: documentation, stable backport potential

#42 Speed up CI workflow and tox
  .github/workflows/test_latest_versions.yml
  tox.ini
Labels: stable backport potential, cicd

#44 Remove Windows from README badge
  README.md
Labels: documentation, stable backport potential

#45 Update explanation of config recovery output
  qiskit_addon_sqd/configuration_recovery.py
Labels: documentation, stable backport potential

#48 Add unit tests for configuration recovery module
  qiskit_addon_sqd/configuration_recovery.py
  test/test_configuration_recovery.py
Labels: stable backport potential, test

#55 Add release note for div-by-zero bugfix
  releasenotes/notes/divzero-a6090f6555d1c716.yaml
Labels: documentation

#62 Update Dice how-to
  docs/how_tos/integrate_dice_solver.ipynb
Labels: documentation, stable backport potential

#64 Fix dead link in Dice solver how-to
  docs/how_tos/integrate_dice_solver.ipynb
Labels: documentation, stable backport potential
