Repository Qiskit/qiskit-addon-sqd, pull requests merged in 2024-10, with the labels that each got.

#69 Add unit tests, clean up documentation, and add error handling in qubit module.
  qiskit_addon_sqd/qubit.py
  test/test_qubit.py
Labels: documentation, test

#71 Fix bugs in optimize_orbitals related to open-shell workflows
  qiskit_addon_sqd/fermion.py
  releasenotes/notes/oo-bug-occs-3c348b86ee03857f.yaml
Labels: bug

#74 Fix bugs in fermion module affecting open shell systems
  qiskit_addon_sqd/fermion.py
  releasenotes/notes/fermion-bug-2b2ed34f979b1321.yaml
Labels: bug

#76 Add a citation file
  CITATION.bib
  docs/index.rst
Labels: documentation, stable backport potential

#75 Fix GitHub source code links for decorated functions
  docs/conf.py
Labels: stable backport potential

#88 Reorganize API docs
  docs/apidocs/index.rst
  docs/apidocs/qiskit_addon_sqd.configuration_recovery.rst
  docs/apidocs/qiskit_addon_sqd.counts.rst
  docs/apidocs/qiskit_addon_sqd.fermion.rst
  docs/apidocs/qiskit_addon_sqd.qubit.rst
  docs/apidocs/qiskit_addon_sqd.rst
  docs/apidocs/qiskit_addon_sqd.subsampling.rst
  docs/conf.py
  docs/index.rst
  pyproject.toml
  qiskit_addon_sqd/__init__.py
  qiskit_addon_sqd/configuration_recovery.py
  qiskit_addon_sqd/counts.py
  qiskit_addon_sqd/fermion.py
  qiskit_addon_sqd/qubit.py
  qiskit_addon_sqd/subsampling.py
Labels: stable backport potential

#92 Clean up some errors in API docs
  qiskit_addon_sqd/counts.py
  qiskit_addon_sqd/fermion.py
Labels: documentation, stable backport potential
