Repository Qiskit/qiskit-addon-sqd, pull requests merged in 2025-03, with the labels that each got.

#145 Fix documentation on Pauli operator projection
  docs/how_tos/benchmark_pauli_projection.ipynb
Labels: documentation, stable backport potential

#157 tutorial 1 cleanup
  docs/tutorials/01_chemistry_hamiltonian.ipynb
Labels: documentation, stable backport potential

#159 Update landing pages
  README.md
  docs/index.rst
Labels: documentation, stable backport potential

#167 Add development version tests
  .github/workflows/test_development_versions.yml
Labels: cicd

#168 Add minimum version tests
  .github/workflows/test_minimum_versions.yml
Labels: cicd

#173 Add note informing that bitstring matrix will be sorted/deduplicated inside solve_qubit
  qiskit_addon_sqd/qubit.py
Labels: stable backport potential
